org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=rewithered
mod.name=Rewithered
mod.group=me.pajic
mod.version=1.0.9
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Adds wither potions and arrows and integrates them into the world
mod.sources_url=https://github.com/pajicadvance/rewithered
mod.homepage_url=https://modrinth.com/mod/rewithered
mod.issues_url=https://github.com/pajicadvance/rewithered/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]
deps.mixson=[VERSIONED]

publish.modrinth=UY95etAw
publish.curseforge=1335211
publish.github=false
